[package]
name = "shoot"
version = "0.1.0"
edition = "2021"

[dependencies]
log = "0.4.20"
cgmath = "0.18.0"
gamekit = { version = "0.1.0", path = "../../gamekit" }

[build-dependencies]
gamekit = { version = "0.1.0", path = "../../gamekit" }
